### ISSUE TITLE
win/lose conditions

### ISSUE THREAD

**Issue by cmavelis** [Aveli-games/infestation#26]
First pass: 
win conditions (meet one):
- [x] Cleanse all domes (available after 3 minutes)
- [x] Generate 500 research points

lose conditions (meet one)
- [x] Lose HQ
- [x] Lose 10 domes

**Comment by avelitj12** [comment]
Found 2000 research to be way too hard, decreased to 500, almost did it, but ran out of food so couldn't save HQ!
